[engine]
detach_keys="ctrl-q,ctrl-q"
env = [
  "http_proxy=http://host.docker.internal:2080",
  "https_proxy=http://host.docker.internal:2080",
  "all_proxy=http://host.docker.internal:2080",
  "no_proxy=localhost,127.0.0.1,::1,.local,.lan,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
  "HTTP_PROXY=http://host.docker.internal:2080",
  "HTTPS_PROXY=http://host.docker.internal:2080",
  "ALL_PROXY=http://host.docker.internal:2080",
  "NO_PROXY=localhost,127.0.0.1,::1,.local,.lan,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
]

[containers]
http_proxy = false
env = [
  "http_proxy=http://host.docker.internal:2080",
  "https_proxy=http://host.docker.internal:2080",
  "all_proxy=http://host.docker.internal:2080",
  "no_proxy=localhost,127.0.0.1,::1,.local,.lan,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
  "HTTP_PROXY=http://host.docker.internal:2080",
  "HTTPS_PROXY=http://host.docker.internal:2080",
  "ALL_PROXY=http://host.docker.internal:2080",
  "NO_PROXY=localhost,127.0.0.1,::1,.local,.lan,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
]
